feat: domain trade and webhosting product
ovhlabs/go-sdk pull request #3
Opened 2017-01-07 23:42 UTC by MarcAudefroy

feat: add push webhosting product into a cart
feat: add trade cli

2017-01-08 19:44 UTC, yesnault requested changes
Why 404 in err ?

2017-01-08 19:44 UTC, yesnault commented on ovh/ovhcli/order/domains.go
> +			Duration:    "P1Y",
why not arg with default value ?

2017-01-08 19:44 UTC, yesnault commented on ovh/ovhcli/order/domains.go
> +		for i := range serviceOptions {
for _, serviceOption := range servicesOptions { no ?

2017-01-08 19:44 UTC, yesnault commented on ovh/ovhcli/order/domains.go
> +			err = fmt.Errorf("Cannot find service options of type trade for domain %s", domain)
common.Exit("Cannot find service options of type trade for domain %s", domain)

2017-01-08 19:44 UTC, yesnault commented on ovh/ovhcli/order/domains.go
> +			err := fmt.Errorf("Missing withOwner option")
common.Exit("Missing withOwner option") or common.WrongUsage by adding new arg for err description.

2017-01-08 19:44 UTC, yesnault commented on ovh/orderwebhosting.go
> +		return nil, errors.New("Error 404: \"Invalid Cart ID\"")
why 404 and not just Cart ID cannot be null ?

2017-01-09 20:51 UTC, yesnault approved these changes

2017-01-10 08:39 UTC, fsamin approved these changes
LGTM

2017-01-10 08:40 UTC, merged