fix create
ovhlabs/go-sdk pull request #8
Opened 2017-01-12 20:43 UTC by MarcAudefroy

2017-01-12 22:01 UTC, yesnault approved these changes

2017-01-13 13:25 UTC, fsamin approved these changes

2017-01-13 13:26 UTC, fsamin requested changes
would you put a better comment on what is fixed in this PR ? (done)

2017-01-13 16:02 UTC, yesnault approved these changes

2017-01-13 16:06 UTC, merged